default: true

# Disable most common problematic rules
MD013: false # Line length
MD024: false # Multiple headers with the same content
MD028: false # Blank line inside blockquote
MD033: false # Inline HTML
MD036: false # Emphasis used instead of a header
MD041: false # First line in file should be a top level header
